# iris-datapipe development environment
version: '3.7'

services:
  datapipe:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: datapipe
    init: true
    ports:
    - 1972:1972
    - 52773:52773
    volumes:
    - .:/app
    networks:
      - datapipe-network

networks:
  datapipe-network:
    name: datapipe-network