# iris-datapipe development environment
version: '3.7'

services:
  datapipe:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: datapipe
    command: --check-caps false
    init: true
    ports:
    - "51773:51773"
    - "52773:52773"
    volumes:
    - .:/app
    networks:
      - datapipe-network

networks:
  datapipe-network:
    name: datapipe-network