Class DataPipe.Test.REST.Msg.PersonReq Extends (Ens.Request, PersonData)
{

Storage Default
{
<Data name="PersonReqDefaultData">
<Subscript>"PersonReq"</Subscript>
<Value name="1">
<Value>XRequestId</Value>
</Value>
<Value name="2">
<Value>XForwardedHost</Value>
</Value>
<Value name="3">
<Value>SSN</Value>
</Value>
<Value name="4">
<Value>Name</Value>
</Value>
<Value name="5">
<Value>Surname</Value>
</Value>
<Value name="6">
<Value>Company</Value>
</Value>
<Value name="7">
<Value>DOB</Value>
</Value>
</Data>
<DefaultData>PersonReqDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
